[package]

name = "rust-keepass-cli"
version = "0.0.1"
authors = ["Jonas Lindmark <jonas.lindmark@gmail.com>"]

[dependencies.keepass]
git = "https://github.com/raymontag/rust-keepass.git"

[dependencies]
rpassword = "0.0.6"
